### ISSUE TITLE
Chore: Clear Stale [`JS`] Code and Init `Phoenix` Project

### ISSUE THREAD

**Issue by nelsonic** [dwyl/calendar#22]
At present the [`/lib`](https://github.com/dwyl/calendar/tree/781031072bf3b569e3c1099d7659238a3cdf3e5b/lib) directory has some stale `JS` code. 
e.g: [`/lib/google_oauth_handler.js`](https://github.com/dwyl/calendar/blame/781031072bf3b569e3c1099d7659238a3cdf3e5b/lib/google_oauth_handler.js) and [`server.js`](https://github.com/dwyl/calendar/blame/781031072bf3b569e3c1099d7659238a3cdf3e5b/server.js) and [`package.json`](https://github.com/dwyl/calendar/blame/781031072bf3b569e3c1099d7659238a3cdf3e5b/package.json)
I wrote it so have no issues retiring it so that we can revive this project and make it _useful_. 👌 

# Todo

+ [x] `DELETE` (`git rm`) the `/lib` and `test` directories
+ [x] `DELETE` `server.js` and `package.json`
+ [x] Create a `new` `Phoenix` project using the latest `phx.new` 
+ [x] Setup `GitHub Actions` (CI/CD) so that we know the build is passing
  + [x] Borrow from https://github.com/dwyl/mvp/tree/main/.github

**Comment by nelsonic** [comment]
```sh
mix phx.new cal --no-mailer --no-dashboard
```
